/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
//       HyperLinks links = new HyperLinks();
//       links.hyperLinksCount();
//       links.endTest();
//        SearchAmazon search = new SearchAmazon();
//        search.searchAmazon();
//        search.endTest();
        BookMyShow book = new BookMyShow();
        book.bookMyShow();
        book.endTest();
//        Frames frame = new Frames();
//        frame.frames();
//        frame.endTest();
//        Imdb i = new Imdb();
//        i.imdb();
//        i.endTest();
//        WindowHandle wh = new WindowHandle();
//        wh.handle();
//        wh.endTest();
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
